### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: Настройка, развертывание и запуск в Azure
metadata:
  title: Настройка, развертывание и запуск в Azure
  description: Настройка, развертывание и запуск в Azure
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40444155"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
