### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="145d2-101">Настройка, развертывание и запуск в Azure</span><span class="sxs-lookup"><span data-stu-id="145d2-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="145d2-102">Настройка, развертывание и запуск в Azure</span><span class="sxs-lookup"><span data-stu-id="145d2-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="145d2-103">Настройка, развертывание и запуск в Azure</span><span class="sxs-lookup"><span data-stu-id="145d2-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 12d10497be5490db01c1822d11cd81f3145588f5
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43179953"
durationInMinutes: 12
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
